version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  checklint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  coverage:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run test:codecov
workflows:
  code-style:
    jobs:
      - checklint
  node-tests:
    jobs:
      - node/test
      - coverage
